### PR TITLE
added highlight colour

### PR DESCRIPTION
**Pull request by owenvachell**
This is an implementation of the [suggestion](https://github.com/hadynz/obsidian-kindle-plugin/issues/36) from [BradenKoh27](https://github.com/BradenKoh27) to add highlight colours. the plugin failed to load in Obsidian from source so I haven't been able to test.

### CODE REVIEW

**Review by hadynz — CHANGES_REQUESTED** [review]
You just need to make one more change expose the new property to the notes template:

**Modify the `RenderTemplate` model. This is the model that get passed to Nunjucks**
Add a nullable `color` field to `RenderTemplate.highlights` [here][1]. You don't have to worry about doing any mapping as that is done automatically through [destructuring][2] here.

Can I also ask you to [update the README.md][3] file to add a reference to the new `color` field that you've added? You can also call out the following:

- List all the possible color combinations that are possible. You might need to refer to a native Kindle app to see what's available
- This field will only be populated when syncing via Amazon, not via uploading My Clippings

Thank you so much for the PR. I can see that people who use colors consciously with their highlights could find this really useful.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/pull/37/files#diff-41b76dc43070308a3e3f270eb861b65259fd377aef32fe30e32ef61b07d086f6R37-R41
[2]: https://github.com/hadynz/obsidian-kindle-plugin/blob/master/src/renderer.ts#L15-L29
[3]: https://github.com/hadynz/obsidian-kindle-plugin/blob/master/README.md#template-tags

**Comment by owenvachell** [comment]
I've just made another push with the requested changes. Hopefully this is all ok. Still new to GitHub pull requests. Please let me know if I did anything wrong.

**Comment by hadynz** [comment]
> I've just made another push with the requested changes. Hopefully this is all ok. Still new to GitHub pull requests. Please let me know if I did anything wrong.
The PR looks good. You've done a great job for a first time contribution.

You've raised the urgency for me to add a lot of test coverage to the plugin. I've got very few tests as I was mainly focused on shipping out a MVP of the plugin. Having tests would have given you a lot more confidence and feedback that your changes will work as expected.

I will test your change locally after it is merged. If it works well on my machine, I'll increment the package number and push a new release.

**Review by hadynz — APPROVED** [review]

**Comment by owenvachell** [comment]
> > I've just made another push with the requested changes. Hopefully this is all ok. Still new to GitHub pull requests. Please let me know if I did anything wrong.
> > The PR looks good. You've done a great job for a first time contribution.
> 
> You've raised the urgency for me to add a lot of test coverage to the plugin. I've got very few tests as I was mainly focused on shipping out a MVP of the plugin. Having tests would have given you a lot more confidence and feedback that your changes will work as expected.
> 
> I will test your change locally after it is merged. If it works well on my machine, I'll increment the package number and push a new release.

Awesome! Thanks for letting me know and accepting my changes. Feels good to give something back. And thanks for the awesome plugin. 👍🏻

**Pull request merged**
